FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./

RUN ls -la || true
RUN if [ -f package-lock.json ]; then npm ci; else npm install; fi

COPY . .

EXPOSE 5000

CMD ["npm", "start"]